### ISSUE TITLE
privateRouter undefined

### ISSUE THREAD

**Issue by brandynbennett** [nickiaconis/ember-prefetch#134]
On Ember 3.7 and 3.9, when switching from 3.0.1 to 3.1.0 of this addon an error gets thrown from `diff-route-info.js` `Cannot read property 'getRoute' of undefined`. 

In the `prefetch` service `var privateRouter = this.router._router._routerMicrolib;` is undefined. Specifically `_routerMicrolib`, is not a property.

**Comment by pzuraq** [comment]
Hey @brandynbennett! We just encountered this issue as well in our test suite, it turned out the reason was that the Prefetch service was being created before the application/router was setup, in a `beforeEach` hook. I would check to see if that's happening in your tests, since it could be the root cause.

**Comment by brandynbennett** [comment]
@pzuraq Thanks for the tip. That was the issue. I was accessing the application router in an instance initializer.
